baseURL = "https://mariano-fernandez.github.io/"
title = "~/mariano"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true

[pagination]
pagerSize = 10

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = false

[params]
author = "Mariano Fernandez"
description = "Developer blog, projects, and portfolio"
keywords = "blog,developer,portfolio,cv"
info = ["Breaking prod so you don't have to"]
avatarURL = "images/avatar.png"
dateFormat = "January 2, 2006"
colorScheme = "dark"
hideColorSchemeToggle = false
customCSS = ["css/custom.css"]
# Set to false to hide the Blog section from the site
enableBlog = false

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/mariano-fernandez/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/marianoluisfernandez/"

[[params.social]]
name = "GitLab"
icon = "fa-brands fa-gitlab fa-2x"
weight = 3
url = "https://gitlab.com/mariano.fernandez"

[[params.social]]
name = "Last.fm"
icon = "fa-brands fa-lastfm fa-2x"
weight = 4
url = "http://www.last.fm/user/kurtcomlf"

[[params.social]]
name = "Flickr"
icon = "fa-brands fa-flickr fa-2x"
weight = 5
url = "https://www.flickr.com/people/kurtcomlf/"

[[menu.main]]
name = "Home"
weight = 1
url = "/"

[[menu.main]]
name = "Blog"
weight = 2
url = "/posts/"

[[menu.main]]
name = "About"
weight = 3
url = "/about/"
